# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae3fcfe1da5d83834d497981fa8f1410a80c85c2604313f344c89f2db79d50e35fe6bc26607ef419b8f166451ce1c5d6de93afabfae7c176493024eea812ceb2

test:
  secret_key_base: e697a872fd33ca1b935ce7a68535c58dae16e1f046572ba341cb3f3b684f0f06eb95f2a0b54380265fb8b24033f2834da5073db8b01340d34ae6ebaf8a630f8b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
